import Link from "next/link";
import { getDashboardData } from "@/lib/dashboard";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { StatusBadge, CondicionBadge } from "@/components/articulos/status-badge";
import { AuditoriaReminder } from "@/components/dashboard/auditoria-reminder";
import { formatDiasDesde, formatFecha, MOVIMIENTO_LABELS } from "@/lib/utils";
export const dynamic = "force-dynamic";
export default async function DashboardPage() { const { totales, topPerdidos, topDanados, fueraMasTiempo, recientes } = await getDashboardData(); return <div><PageHeader title="Dashboard" description="Resumen del inventario de materiales y herramientas" action={<Link href="/articulos/nuevo" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Agregar artículo</Link>} /><AuditoriaReminder /><div className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{label:"Total",value:totales.total},{label:"Stock",value:totales.stock},{label:"Asignados",value:totales.asignado},{label:"Prestados",value:totales.prestado},{label:"Dañados",value:totales.danados},{label:"Perdidos",value:totales.perdido},{label:"Terminados",value:totales.terminado}].map((x)=><Card key={x.label}><p className="text-sm text-slate-500">{x.label}</p><p className="mt-1 text-3xl font-bold">{x.value}</p></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardTitle>Herramientas con más tiempo fuera</CardTitle><ul className="mt-4 divide-y divide-slate-100">{fueraMasTiempo.map((a)=><li key={a.id} className="py-3 text-sm"><Link href={`/articulos/${a.id}`} className="font-medium text-blue-700 hover:underline">{a.nombre}</Link><div className="mt-1 flex flex-wrap gap-2"><StatusBadge status={a.status}/><CondicionBadge condicion={a.condicion}/><Badge>{formatDiasDesde(a.fechaSalida)}</Badge></div><p className="mt-1 text-slate-500">{a.trabajadorActual?.nombre ?? "Sin trabajador"}</p></li>)}{fueraMasTiempo.length===0&&<p className="mt-4 text-sm text-slate-500">No hay artículos fuera.</p>}</ul></Card><Card><CardTitle>Movimientos recientes</CardTitle><ul className="mt-4 divide-y divide-slate-100">{recientes.map((m)=><li key={m.id} className="py-3 text-sm"><Badge tone="info">{MOVIMIENTO_LABELS[m.tipo]}</Badge><p className="mt-1 font-medium">{m.articulo.nombre}</p><p className="text-xs text-slate-500">{m.trabajador?.nombre ?? "Sin trabajador"} - {formatFecha(m.fecha)}</p></li>)}</ul></Card><Card><CardTitle>Más artículos perdidos</CardTitle>{topPerdidos.map((t)=><p key={t.id} className="mt-3 flex justify-between text-sm"><span>{t.nombre}</span><strong>{t.total}</strong></p>)}{topPerdidos.length===0&&<p className="mt-4 text-sm text-slate-500">Sin pérdidas registradas.</p>}</Card><Card><CardTitle>Más artículos dañados</CardTitle>{topDanados.map((t)=><p key={t.id} className="mt-3 flex justify-between text-sm"><span>{t.nombre}</span><strong>{t.total}</strong></p>)}{topDanados.length===0&&<p className="mt-4 text-sm text-slate-500">Sin daños registrados.</p>}</Card></div></div>; }
