import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardTitle } from "@/components/ui/card";
import { StatusBadge, CondicionBadge } from "@/components/articulos/status-badge";
import { MovimientoForm } from "@/components/forms/movimiento-form";
import { DevolucionForm } from "@/components/forms/devolucion-form";
import { ArticuloForm } from "@/components/forms/articulo-form";
import { formatDiasDesde, formatFecha, MOVIMIENTO_LABELS } from "@/lib/utils";
import { demoArticulos, demoMovimientos, demoTrabajadores, isDemoMode } from "@/lib/demo-data";
export const dynamic="force-dynamic";
export default async function ArticuloDetallePage({params}:{params:Promise<{id:string}>}){const {id}=await params; const [articulo,trabajadores]=isDemoMode ? [demoArticulos.find((a)=>a.id===id) ? { ...demoArticulos.find((a)=>a.id===id)!, movimientos: demoMovimientos.filter((m)=>m.articuloId===id) } : null, demoTrabajadores] : await Promise.all([prisma.articulo.findUnique({where:{id},include:{trabajadorActual:true,movimientos:{include:{trabajador:true},orderBy:{fecha:"desc"}}}}),prisma.trabajador.findMany({where:{activo:true},orderBy:{nombre:"asc"}})]); if(!articulo) notFound(); return <div><PageHeader title={articulo.nombre} description={articulo.categoria} action={<Link href="/articulos" className="text-sm text-blue-700 hover:underline">Volver</Link>}/><div className="mb-6 grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-slate-500">Status</p><div className="mt-2"><StatusBadge status={articulo.status}/></div></Card><Card><p className="text-sm text-slate-500">Condición</p><div className="mt-2"><CondicionBadge condicion={articulo.condicion}/></div></Card><Card><p className="text-sm text-slate-500">Lo tiene</p><p className="mt-2 font-medium">{articulo.trabajadorActual?.nombre ?? "Inventario"}</p></Card><Card><p className="text-sm text-slate-500">Tiempo fuera</p><p className="mt-2 font-medium">{formatDiasDesde(articulo.fechaSalida)}</p></Card></div><div className="mb-8 grid gap-6 lg:grid-cols-2"><Card><CardTitle>Datos editables</CardTitle><div className="mt-4"><ArticuloForm articulo={articulo}/></div></Card><Card><CardTitle>Acciones</CardTitle>{articulo.status==="STOCK" ? <div className="mt-4 grid gap-6"><div><h3 className="mb-3 font-medium">Asignación permanente</h3><MovimientoForm articuloId={articulo.id} trabajadores={trabajadores} tipo="asignar"/></div><div><h3 className="mb-3 font-medium">Préstamo temporal</h3><MovimientoForm articuloId={articulo.id} trabajadores={trabajadores} tipo="prestar"/></div></div> : ["ASIGNADO","PRESTADO"].includes(articulo.status) ? <div className="mt-4"><DevolucionForm articuloId={articulo.id}/></div> : <p className="mt-4 text-sm text-slate-500">Este artículo ya no está disponible para préstamo o asignación.</p>}</Card></div><Card><CardTitle>Historial imborrable</CardTitle><table className="mt-4 w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="py-2">Fecha</th><th>Movimiento</th><th>Trabajador</th><th>Status</th><th>Condición</th><th>Comentarios</th></tr></thead><tbody>{articulo.movimientos.map((m)=><tr key={m.id} className="border-t border-slate-100"><td className="py-2">{formatFecha(m.fecha)}</td><td>{MOVIMIENTO_LABELS[m.tipo]}</td><td>{m.trabajador?.nombre ?? "—"}</td><td>{m.statusAnterior ?? "—"} → {m.statusNuevo ?? "—"}</td><td>{m.condicionAnterior ?? "—"} → {m.condicionNueva ?? "—"}</td><td className="text-slate-500">{m.comentarios ?? "—"}</td></tr>)}</tbody></table></Card></div>}
