import Link from "next/link";
import { Suspense } from "react";
import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/layout/page-header";
import { Card } from "@/components/ui/card";
import { ArticulosFilters } from "@/components/articulos/filters";
import { StatusBadge, CondicionBadge } from "@/components/articulos/status-badge";
import { formatDiasDesde, formatFecha } from "@/lib/utils";
import { demoArticulos, isDemoMode } from "@/lib/demo-data";
import type { ArticuloStatus, CondicionArticulo } from "@prisma/client";
export const dynamic = "force-dynamic";
export default async function ArticulosPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { const sp=await searchParams; const categorias=isDemoMode ? Array.from(new Set(demoArticulos.map((x)=>x.categoria))) : (await prisma.articulo.findMany({select:{categoria:true},distinct:["categoria"],orderBy:{categoria:"asc"}})).map((x)=>x.categoria); const articulos=isDemoMode ? demoArticulos.filter((a)=>(!sp.status||a.status===sp.status)&&(!sp.condicion||a.condicion===sp.condicion)&&(!sp.categoria||a.categoria===sp.categoria)&&(!sp.q||`${a.nombre} ${a.categoria} ${a.numeroSerie ?? ""}`.toLowerCase().includes(sp.q.toLowerCase()))) : await prisma.articulo.findMany({ where:{ ...(sp.status?{status:sp.status as ArticuloStatus}:{}), ...(sp.condicion?{condicion:sp.condicion as CondicionArticulo}:{}), ...(sp.categoria?{categoria:sp.categoria}:{}), ...(sp.q?{OR:[{nombre:{contains:sp.q,mode:"insensitive"}},{categoria:{contains:sp.q,mode:"insensitive"}},{numeroSerie:{contains:sp.q,mode:"insensitive"}}]}:{}) }, include:{trabajadorActual:true}, orderBy:{updatedAt:"desc"} }); return <div><PageHeader title="Artículos" description="Inventario completo. Los artículos no se eliminan." action={<Link href="/articulos/nuevo" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Agregar artículo</Link>} /><Suspense><ArticulosFilters categorias={categorias}/></Suspense><Card className="overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="px-4 py-3">Artículo</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Serie</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Condición</th><th className="px-4 py-3">Trabajador</th><th className="px-4 py-3">Tiempo fuera</th></tr></thead><tbody>{articulos.map((a)=><tr key={a.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><Link href={`/articulos/${a.id}`} className="font-medium text-blue-700 hover:underline">{a.nombre}</Link><p className="text-xs text-slate-400">Alta {formatFecha(a.fechaRegistro)}</p></td><td className="px-4 py-3">{a.categoria}</td><td className="px-4 py-3 text-slate-500">{a.numeroSerie ?? "—"}</td><td className="px-4 py-3"><StatusBadge status={a.status}/></td><td className="px-4 py-3"><CondicionBadge condicion={a.condicion}/></td><td className="px-4 py-3">{a.trabajadorActual?.nombre ?? "—"}</td><td className="px-4 py-3">{formatDiasDesde(a.fechaSalida)}</td></tr>)}</tbody></table>{articulos.length===0&&<p className="p-8 text-center text-sm text-slate-500">No hay artículos con estos filtros.</p>}</Card></div>; }
