"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Articulo, Trabajador } from "@prisma/client";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/forms/label";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { CondicionBadge } from "@/components/articulos/status-badge";

type TrabajadorConArticulos = Trabajador & { articulosActuales: Articulo[] };
export function AuditoriaForm({ trabajadores }: { trabajadores: TrabajadorConArticulos[] }) { const router=useRouter(); const [trabajadorId,setTrabajadorId]=useState(trabajadores[0]?.id ?? ""); const [error,setError]=useState(""); const trabajador=useMemo(()=>trabajadores.find((t)=>t.id===trabajadorId),[trabajadores,trabajadorId]); async function onSubmit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if(!trabajador) return; const fd=new FormData(e.currentTarget); const detalles=trabajador.articulosActuales.map((a)=>({ articuloId:a.id, condicionConfirmada:fd.get(`condicion-${a.id}`), sigueEnPosesion:fd.get(`posee-${a.id}`)==="true", comentarios:fd.get(`comentarios-${a.id}`)||null })); const res=await fetch("/api/auditorias",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trabajadorId,comentarios:fd.get("comentarios")||null,detalles})}); const data=await res.json(); if(!res.ok){setError(data.error??"Error al guardar auditoría");return;} router.push("/auditorias"); router.refresh(); } return <form onSubmit={onSubmit}><Field label="Trabajador"><Select value={trabajadorId} onChange={(e)=>setTrabajadorId(e.currentTarget.value)}><option value="">Seleccionar</option>{trabajadores.map((t)=><option key={t.id} value={t.id}>{t.nombre}</option>)}</Select></Field>{trabajador?.articulosActuales.length ? <div className="mb-4 overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-3">Artículo</th><th className="p-3">Condición actual</th><th className="p-3">Sigue en posesión</th><th className="p-3">Condición confirmada</th><th className="p-3">Comentarios</th></tr></thead><tbody>{trabajador.articulosActuales.map((a)=><tr key={a.id} className="border-t border-slate-100"><td className="p-3 font-medium">{a.nombre}</td><td className="p-3"><CondicionBadge condicion={a.condicion}/></td><td className="p-3"><Select name={`posee-${a.id}`} defaultValue="true"><option value="true">Sí</option><option value="false">No</option></Select></td><td className="p-3"><Select name={`condicion-${a.id}`} defaultValue={a.condicion}><option value="OPTIMO">Óptimo</option><option value="DANADO">Dañado</option><option value="PERDIDO">Perdido</option><option value="TERMINADO">Terminado</option></Select></td><td className="p-3"><Input name={`comentarios-${a.id}`} /></td></tr>)}</tbody></table></div> : <p className="mb-4 text-sm text-slate-500">Este trabajador no tiene artículos asignados.</p>}<Field label="Comentarios generales"><Input name="comentarios" /></Field>{error && <p className="mb-4 text-sm text-red-600">{error}</p>}<Button disabled={!trabajador?.articulosActuales.length}>Guardar auditoría</Button></form>; }
